/**
 * wordData.js — Static word lists for the typing test.
 * Exports WORDS_ENGLISH (~500 common English words) and
 * WORDS_INDONESIA (~500 common Indonesian words).
 */

export const WORDS_ENGLISH = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
  "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
  "but", "his", "by", "from", "they", "we", "say", "her", "she", "or",
  "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know",
  "take", "people", "into", "year", "your", "good", "some", "could",
  "them", "see", "other", "than", "then", "now", "look", "only", "come",
  "its", "over", "think", "also", "back", "after", "use", "two", "how",
  "our", "work", "first", "well", "way", "even", "new", "want", "because",
  "any", "these", "give", "day", "most", "us", "great", "between", "need",
  "large", "often", "hand", "high", "place", "hold", "turn", "here", "why",
  "help", "put", "different", "away", "again", "off", "went", "old", "number",
  "great", "tell", "men", "say", "small", "every", "found", "still", "between",
  "name", "should", "home", "big", "give", "air", "line", "set", "own",
  "under", "read", "last", "never", "us", "left", "end", "along", "while",
  "might", "next", "sound", "below", "saw", "something", "thought", "both",
  "few", "those", "always", "show", "large", "often", "together", "asked",
  "house", "world", "going", "want", "school", "important", "until", "form",
  "food", "keep", "children", "feet", "land", "side", "without", "boy",
  "once", "animal", "life", "enough", "took", "four", "head", "above",
  "kind", "began", "almost", "live", "page", "got", "earth", "need",
  "far", "hand", "high", "place", "year", "came", "show", "every",
  "good", "give", "our", "under", "name", "very", "through", "just",
  "form", "sentence", "great", "think", "say", "help", "low", "line",
  "differ", "turn", "cause", "much", "mean", "before", "move", "right",
  "boy", "old", "too", "same", "tell", "does", "set", "three", "want",
  "air", "well", "also", "play", "small", "end", "put", "home", "read",
  "hand", "port", "large", "spell", "add", "even", "land", "here",
  "must", "big", "high", "such", "follow", "act", "why", "ask", "men",
  "change", "went", "light", "kind", "off", "need", "house", "picture",
  "try", "again", "animal", "point", "mother", "world", "near", "build",
  "self", "earth", "father", "head", "stand", "own", "page", "should",
  "country", "found", "answer", "school", "grow", "study", "still",
  "learn", "plant", "cover", "food", "sun", "four", "between", "state",
  "keep", "eye", "never", "last", "let", "thought", "city", "tree",
  "cross", "farm", "hard", "start", "might", "story", "saw", "far",
  "sea", "draw", "left", "late", "run", "while", "press", "close",
  "night", "real", "life", "few", "north", "open", "seem", "together",
  "next", "white", "children", "begin", "got", "walk", "example",
  "ease", "paper", "group", "always", "music", "those", "both", "mark",
  "book", "letter", "until", "mile", "river", "car", "feet", "care",
  "second", "enough", "plain", "girl", "usual", "young", "ready",
  "above", "ever", "red", "list", "though", "feel", "talk", "bird",
  "soon", "body", "dog", "family", "direct", "pose", "leave", "song",
  "measure", "door", "product", "black", "short", "numeral", "class",
  "wind", "question", "happen", "complete", "ship", "area", "half",
  "rock", "order", "fire", "south", "problem", "piece", "told", "knew",
  "pass", "since", "top", "whole", "king", "space", "heard", "best",
  "hour", "better", "true", "during", "hundred", "five", "remember",
  "step", "early", "hold", "west", "ground", "interest", "reach",
  "fast", "verb", "sing", "listen", "six", "table", "travel", "less",
  "morning", "ten", "simple", "several", "vowel", "toward", "war",
  "lay", "against", "pattern", "slow", "center", "love", "person",
  "money", "serve", "appear", "road", "map", "rain", "rule", "govern",
  "pull", "cold", "notice", "voice", "unit", "power", "town", "fine",
  "drive", "lead", "cry", "dark", "machine", "note", "wait", "plan",
  "figure", "star", "box", "noun", "field", "rest", "correct", "able",
  "pound", "done", "beauty", "drive", "stood", "contain", "front",
  "teach", "week", "final", "gave", "green", "oh", "quick", "develop",
  "ocean", "warm", "free", "minute", "strong", "special", "mind",
  "behind", "clear", "tail", "produce", "fact", "street", "inch",
  "multiply", "nothing", "course", "stay", "wheel", "full", "force",
  "blue", "object", "decide", "surface", "deep", "moon", "island",
  "foot", "system", "busy", "test", "record", "boat", "common",
  "gold", "possible", "plane", "stead", "dry", "wonder", "laugh",
  "thousand", "ago", "ran", "check", "game", "shape", "equate",
  "hot", "miss", "brought", "heat", "snow", "tire", "bring", "yes",
  "distant", "fill", "east", "paint", "language", "among", "grand",
  "ball", "yet", "wave", "drop", "heart", "am", "present", "heavy",
  "dance", "engine", "position", "arm", "wide", "sail", "material",
  "size", "vary", "settle", "speak", "weight", "general", "ice",
  "matter", "circle", "pair", "include", "divide", "syllable", "felt",
  "perhaps", "pick", "sudden", "count", "square", "reason", "length",
  "represent", "art", "subject", "region", "energy", "hunt", "probable",
  "bed", "brother", "egg", "ride", "cell", "believe", "fraction",
  "forest", "sit", "race", "window", "store", "summer", "train",
  "sleep", "prove", "lone", "leg", "exercise", "wall", "catch",
  "mount", "wish", "sky", "board", "joy", "winter", "sat", "written",
  "wild", "instrument", "kept", "glass", "grass", "cow", "job",
  "edge", "sign", "visit", "past", "soft", "fun", "bright", "gas",
  "weather", "month", "million", "bear", "finish", "happy", "hope",
  "flower", "clothe", "strange", "gone", "jump", "baby", "eight",
  "village", "meet", "root", "buy", "raise", "solve", "metal",
  "whether", "push", "seven", "paragraph", "third", "shall", "held",
  "hair", "describe", "cook", "floor", "either", "result", "burn",
  "hill", "safe", "cat", "century", "consider", "type", "law",
  "bit", "coast", "copy", "phrase", "silent", "tall", "sand",
  "soil", "roll", "temperature", "finger", "industry", "value",
  "fight", "lie", "beat", "excite", "natural", "view", "sense",
  "capital", "will", "kill", "afraid", "dead", "rose", "skin",
  "story", "told", "colony", "bring", "opposite", "pound"
];

export const WORDS_INDONESIA = [
  "yang", "dan", "di", "ini", "itu", "dengan", "untuk", "tidak", "ada",
  "dari", "dalam", "akan", "pada", "juga", "ke", "karena", "bisa",
  "sudah", "saya", "kita", "mereka", "dia", "kami", "kamu", "anda",
  "lebih", "atau", "tetapi", "jika", "maka", "seperti", "oleh", "saat",
  "setelah", "sebelum", "antara", "bagi", "tentang", "bahwa", "ketika",
  "hanya", "sangat", "masih", "sudah", "belum", "pernah", "selalu",
  "sering", "jarang", "kadang", "mungkin", "harus", "boleh", "perlu",
  "ingin", "mau", "dapat", "mampu", "tahu", "lihat", "dengar", "rasa",
  "pikir", "kata", "bilang", "cerita", "tanya", "jawab", "buat", "beri",
  "ambil", "bawa", "pergi", "datang", "pulang", "masuk", "keluar",
  "naik", "turun", "jalan", "lari", "duduk", "berdiri", "tidur",
  "makan", "minum", "kerja", "belajar", "main", "baca", "tulis",
  "bicara", "diam", "tunggu", "cari", "temukan", "simpan", "buang",
  "buka", "tutup", "mulai", "selesai", "berhenti", "lanjut", "ubah",
  "tambah", "kurang", "bagi", "kali", "sama", "beda", "besar", "kecil",
  "panjang", "pendek", "tinggi", "rendah", "lebar", "sempit", "tebal",
  "tipis", "berat", "ringan", "cepat", "lambat", "keras", "lembut",
  "panas", "dingin", "basah", "kering", "bersih", "kotor", "baru",
  "lama", "muda", "tua", "hidup", "mati", "baik", "buruk", "benar",
  "salah", "mudah", "sulit", "aman", "bahaya", "senang", "sedih",
  "marah", "takut", "berani", "malu", "bangga", "kaget", "bingung",
  "lelah", "sehat", "sakit", "cantik", "tampan", "jelek", "pintar",
  "bodoh", "rajin", "malas", "jujur", "bohong", "baik", "jahat",
  "kaya", "miskin", "ramai", "sepi", "penuh", "kosong", "dekat",
  "jauh", "dalam", "dangkal", "atas", "bawah", "depan", "belakang",
  "kiri", "kanan", "tengah", "luar", "dalam", "sini", "sana", "situ",
  "rumah", "sekolah", "kantor", "pasar", "toko", "jalan", "kota",
  "desa", "negara", "dunia", "alam", "langit", "bumi", "laut", "sungai",
  "gunung", "hutan", "sawah", "kebun", "taman", "pantai", "pulau",
  "orang", "anak", "ibu", "ayah", "kakak", "adik", "nenek", "kakek",
  "teman", "sahabat", "tetangga", "guru", "murid", "dokter", "polisi",
  "tentara", "petani", "nelayan", "pedagang", "pegawai", "pemimpin",
  "presiden", "menteri", "raja", "rakyat", "masyarakat", "keluarga",
  "bangsa", "pemerintah", "waktu", "hari", "malam", "pagi", "siang",
  "sore", "minggu", "bulan", "tahun", "jam", "menit", "detik", "lalu",
  "sekarang", "nanti", "besok", "kemarin", "dulu", "masa", "zaman",
  "benda", "barang", "alat", "mesin", "kendaraan", "mobil", "motor",
  "sepeda", "kapal", "pesawat", "kereta", "bus", "truk", "buku",
  "kertas", "pena", "pensil", "meja", "kursi", "pintu", "jendela",
  "lantai", "dinding", "atap", "tangga", "kamar", "dapur", "kamar mandi",
  "makanan", "minuman", "nasi", "roti", "sayur", "buah", "daging",
  "ikan", "ayam", "telur", "susu", "air", "teh", "kopi", "gula",
  "garam", "minyak", "baju", "celana", "sepatu", "topi", "tas",
  "jam tangan", "kacamata", "cincin", "kalung", "gelang", "uang",
  "harga", "bayar", "beli", "jual", "dagang", "untung", "rugi",
  "modal", "hutang", "tabungan", "bank", "pasar", "toko", "warung",
  "ilmu", "pengetahuan", "pendidikan", "pelajaran", "ujian", "nilai",
  "prestasi", "juara", "hadiah", "hukuman", "aturan", "hukum",
  "keadilan", "kebenaran", "kebebasan", "perdamaian", "perang",
  "konflik", "masalah", "solusi", "rencana", "tujuan", "harapan",
  "impian", "cita", "usaha", "kerja keras", "semangat", "motivasi",
  "inspirasi", "kreativitas", "inovasi", "teknologi", "sains",
  "matematika", "bahasa", "seni", "musik", "olahraga", "permainan",
  "hiburan", "wisata", "budaya", "tradisi", "adat", "agama", "kepercayaan",
  "doa", "ibadah", "syukur", "maaf", "terima kasih", "tolong", "halo",
  "selamat", "sampai", "jumpa", "perpisahan", "kenangan", "cerita",
  "sejarah", "masa depan", "perubahan", "perkembangan", "kemajuan",
  "kemunduran", "keberhasilan", "kegagalan", "pengalaman", "pelajaran",
  "hikmah", "manfaat", "kerugian", "risiko", "peluang", "tantangan",
  "hambatan", "dukungan", "bantuan", "kerjasama", "persatuan",
  "kebersamaan", "gotong royong", "solidaritas", "empati", "kasih",
  "sayang", "cinta", "persahabatan", "kepercayaan", "kejujuran",
  "kesetiaan", "pengorbanan", "perjuangan", "keteguhan", "kesabaran",
  "keikhlasan", "kerendahan", "keberanian", "kebijaksanaan", "kecerdasan",
  "kreativitas", "produktivitas", "efisiensi", "efektivitas", "kualitas",
  "kuantitas", "standar", "target", "hasil", "dampak", "pengaruh",
  "faktor", "alasan", "sebab", "akibat", "proses", "tahap", "langkah",
  "cara", "metode", "strategi", "teknik", "sistem", "struktur",
  "fungsi", "peran", "tugas", "tanggung jawab", "kewajiban", "hak",
  "kepentingan", "kebutuhan", "keinginan", "harapan", "tuntutan",
  "permintaan", "penawaran", "kesepakatan", "perjanjian", "kontrak",
  "aturan", "kebijakan", "keputusan", "pilihan", "alternatif",
  "kemungkinan", "probabilitas", "kepastian", "ketidakpastian",
  "informasi", "data", "fakta", "bukti", "argumen", "pendapat",
  "pandangan", "perspektif", "sudut pandang", "analisis", "evaluasi",
  "penilaian", "kesimpulan", "rekomendasi", "saran", "kritik",
  "masukan", "umpan balik", "respons", "reaksi", "tanggapan",
  "komunikasi", "interaksi", "hubungan", "koneksi", "jaringan",
  "komunitas", "kelompok", "organisasi", "lembaga", "institusi",
  "perusahaan", "bisnis", "industri", "sektor", "bidang", "area",
  "wilayah", "kawasan", "zona", "lingkungan", "ekosistem", "habitat",
  "sumber daya", "energi", "kekuatan", "kemampuan", "kapasitas",
  "potensi", "bakat", "keahlian", "keterampilan", "kompetensi",
  "profesional", "ahli", "pakar", "spesialis", "generalis", "pemula",
  "mahir", "terampil", "berpengalaman", "berpengetahuan", "terdidik",
  "terlatih", "berkualitas", "unggul", "terbaik", "terpercaya",
  "terkemuka", "terkenal", "populer", "favorit", "pilihan", "andalan"
];
